version: '3.8'

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ["node", "index.js"]