apiVersion: v1
kind: Service
metadata:
  name: myimagekub-service
spec:
  selector:
    app: myimagekub             # Must match the app label in your Deployment
  ports:
    - protocol: TCP
      port: 80                  # External port (what users connect to)
      targetPort: 5050          # Internal container port (your app)
  type: LoadBalancer            # Exposes the service via external IP
